### ISSUE TITLE
Wocki Feedback 10/1

### ISSUE THREAD

**Issue by simplemachine92** [simplemachine92/MarsShotBots#1]
Changes: 
Updated front-end splash
Deployed test, fixed names, 594 bots

In Progress:
Intro animation to site on first visit
Grepping background colors (have a script)
Found Tricky the Pirate and other broken bots
Rares & Super-rares

Issues:
429 from infura

**Comment by owocki** [comment]
firs tthing without clicking the link. the twitter desc/title/image needs updated

**Comment by owocki** [comment]
> Assets Created by ya bois @owocki, @octaviaan & @austingriffith

i like the old "created and abandoned by" messages.  i dont think we want to be seen as putting our name explicitly on the project (though im happy to quietly help u)

**Comment by owocki** [comment]
this copy is hard to read 

https://bits.owocki.com/Jrux01bN

**Comment by owocki** [comment]
favicon n eeds updated! https://bits.owocki.com/KouJpZqJ

**Comment by owocki** [comment]
telegram /discord links are old.  do u want your own telegram group?  https://bits.owocki.com/Jrux01LN

it might be fine to use the MSB one

**Comment by owocki** [comment]
these images are old https://bits.owocki.com/bLuqWgj4

need the new red ones!

**Comment by owocki** [comment]
take a pass at the copy before launching

https://bits.owocki.com/RBuL84Ww

**Comment by owocki** [comment]
is the 5 bot limit actually implmemented? https://bits.owocki.com/z8urKPYo

is 5 the right number?

**Comment by owocki** [comment]
update art link in footer https://bits.owocki.com/xQu6ynYQ
update these links in footer too https://bits.owocki.com/2NulnE04

**Comment by owocki** [comment]
make sure u verify the mainnet contract when u deploy it https://rinkeby.etherscan.io/address/0x93af165ea62f29916d75ad62f021b977d63f95fe

**Comment by codenamejason** [comment]
> is the 5 bot limit actually implmemented? https://bits.owocki.com/z8urKPYo
> 
> is 5 the right number?

I think 5 is a good 'fair launch' number

**Comment by simplemachine92** [comment]
> > is the 5 bot limit actually implmemented? https://bits.owocki.com/z8urKPYo
> > is 5 the right number?
> 
> I think 5 is a good 'fair launch' number

I think it's good for spreading the word :)
